{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zzr.plugin",
    "module": "com.zzr.gradle.plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mki72y4vafgg3hpjecegrbilja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "com.zzr.gradle.plugin-1.0.0.jar",
          "url": "com.zzr.gradle.plugin-1.0.0.jar",
          "size": 2045,
          "sha512": "1ab231fc997f15a39d6a7d0705cda833cd47e8a1dfca48254bc41a2170351dcdefbb42866a4a2fcd8b1a9a730ce4f3e4e53cc98a4bfca948389e1848e9995dd0",
          "sha256": "9c6fa0c1baf094378aa3df81198775bb90ea57cd442197f851261674459be804",
          "sha1": "3f0d433110677423a7e70217ebbed42472da5fa7",
          "md5": "fa87040b3794bf8cbea1705b648094a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "com.zzr.gradle.plugin-1.0.0.jar",
          "url": "com.zzr.gradle.plugin-1.0.0.jar",
          "size": 2045,
          "sha512": "1ab231fc997f15a39d6a7d0705cda833cd47e8a1dfca48254bc41a2170351dcdefbb42866a4a2fcd8b1a9a730ce4f3e4e53cc98a4bfca948389e1848e9995dd0",
          "sha256": "9c6fa0c1baf094378aa3df81198775bb90ea57cd442197f851261674459be804",
          "sha1": "3f0d433110677423a7e70217ebbed42472da5fa7",
          "md5": "fa87040b3794bf8cbea1705b648094a5"
        }
      ]
    }
  ]
}
